### ISSUE TITLE
Need support in Keycloak 19.0.3

### ISSUE THREAD

**Issue by Shailesh-Kala** [9228883664/keycloak-otp-password-authenticator#1]
Hi @9228883664 (@paresh.patel),

We have the same requirement the user needs to login with either password or OTP. We need to setup it on Keycloak 19.0.3 version whose structure is completely different from v16.1.1 so we are not able to understand where we need to make these implementations on our Keycloak v19.0.3.

**Comment by pareshppatelhuf** [comment]
Hi Shailesh,
This plugin will work in kc18 but not working in kc19. Basic core structure is changed in kc19. Need to check again for plugin development.

**Comment by Shailesh-Kala** [comment]
Thanks for your prompt response. 
I was trying to implement the same on KC v16 and I am stuck during the login facing `Invalid user credentials` error 

Flow SS:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/55804406/225572065-4d93f5d5-e949-416a-af80-7ff57e0a6208.png">

Username Form SS:
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/55804406/225574327-31d70472-8fec-4d02-bcce-bb98ac6b733e.png">


Error SS:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/55804406/225574281-283aff0b-ade7-4aa8-84e2-2b48e2f8efa3.png">

**Comment by pareshppatelhuf** [comment]
I have created plugin for direct grant access API and which is not applicable for browser ui authentication. I think you were tried to use same plugin in browser authentication.

**Comment by Shailesh-Kala** [comment]
oh, got it, thank you so much
